### ISSUE TITLE
Document Al36 data slicing and number of electron mismatch

### ISSUE THREAD

**Issue by elcorto** [mala-project/test-data#1]

**Comment by elcorto** [comment]
According to what @RandomDefaultUser mentioned, the Al36 data is from a DFT calc using 36 atoms using a 200x200x200 grid, but the actual `Al_debug_2k_nr0*` files correspond to only sub-slices of that, such that integration over the LDOS won't give us the same number of electrons as used in the  DFT calc.

**Comment by RandomDefaultUser** [comment]
I updated the repository. @elcorto is this now clear from the README or do I need to include more info?

**Comment by elcorto** [comment]
Thanks, that is very useful. Some short questions that came to mind when working through the data.

# Be

```py
>>> np.load('Be2/Be_dos.npy').shape
(11,)
>>> np.load('Be2/Be_ldos.npy').shape
(18, 18, 27, 11)
>>> np.load('Be2/Be_dens.npy').shape
(18, 18, 27)
>>> np.load('Be2/training_data/Be_snapshot1.in.npy').shape
(18, 18, 27, 94)
>>> np.load('Be2/training_data/Be_snapshot1.out.npy').shape
(18, 18, 27, 11)
```

* SNAP grid is 18x18x27 (along a,b,c?) 
* 11 energy grid points
* SNAP length 94

Q: How does one find the min/max energy values?
Q: The arrays in `Be2/Be_ldos.npy` and any of the `Be2/training_data/Be_snapshot*.out.npy` have the same shape, so they are both LDOS on a grid. If so, what is the role of `Be2/Be_ldos.npy`?

# Al

```py
>>> np.load('Al36/Al_dens.npy').shape
(108, 108, 100)
>>> np.load('Al36/Al_dos.npy').shape
(250,)
>>> np.load('Al36/Al_dens.npy').shape
(108, 108, 100)
>>> np.load('Al36/Al_debug_2k_nr0.in.npy').shape
(100, 20, 1, 94)
>>> np.load('Al36/Al_debug_2k_nr0.out.npy').shape
(100, 20, 1, 250)
```

* SNAP grid 108 x 108 x 100 != full calculation grid
* energy grid 250 points

Q: (In case we keep this data #2): The original calculation grid is 200x200x200 I assume? How was the data here taken from the full data set?
Q: There is no equivalent of `Be2/Be_ldos.npy` (i.e. a non-snapshopt file)?

Thanks a lot!

**Comment by RandomDefaultUser** [comment]
Q: How does one find the min/max energy values?

A: The best way is to set the parameters to the correct values (see e.g. https://github.com/mala-project/mala/blob/develop/examples/ex03_postprocess_data.py), i.e.:

```
test_parameters.targets.target_type = "LDOS"
test_parameters.targets.ldos_gridsize = 11
test_parameters.targets.ldos_gridspacing_ev = 2.5
test_parameters.targets.ldos_gridoffset_ev = -5
```

and then do 

```
ldos = mala.LDOS(test_parameters)
energy_grid = ldos.get_energy_grid()
print(energy_grid[0], energy_grid[-1])
```

The "correct values" for the parameters are currently not encoded anywhere. That is a shortcoming we should adress in the future.... 


Q: The arrays in Be2/Be_ldos.npy and any of the Be2/training_data/Be_snapshot*.out.npy have the same shape, so they are both LDOS on a grid. If so, what is the role of Be2/Be_ldos.npy?

A: Oh, that's a mix up. I originally didn't have the `training_data` folder, only one `_ldos.npy` for post processing tests. I can clean this up with #2 . 

Q: (In case we keep this data #2): The original calculation grid is 200x200x200 I assume? How was the data here taken from the full data set?

A: No, it's 100x100x108, from a smaller Aluminium cell. The 200x200x200 is from Al256. 

 Q: There is no equivalent of Be2/Be_ldos.npy (i.e. a non-snapshopt file)?
 
 A: Yes, those would be too big.

**Comment by elcorto** [comment]
Thanks a lot. Most of the above would probably be a good addition to the README, then. Alternatively, we could link from there to this issue and close it.


> Q: (In case we keep this data #2): The original calculation grid is 200x200x200 I assume? How was the data here taken from the full data set?
> 
> A: No, it's 100x100x108, from a smaller Aluminium cell. The 200x200x200 is from Al256.

Thanks. Do you mean 108 x 108 x 100 by any chance, since 

```py
>>> np.load('Al36/Al_dens.npy').shape
(108, 108, 100)
```
?

Also, it may be helpful for users if we could explain the orientation of the slices 100 x 20 x 1 (all `Al36/Al_debug_2k_nr*` files)  relative to the original grid. That might explain what `nr` means as well.

**Comment by RandomDefaultUser** [comment]
Got it, I will update the README further!
Oh yes, I got that mixed up. 

Oh yeah, I think the slices are just the first 100x20x1 slices carved out beginning at (0,0,0). I have to admit I didn't put much thought into getting this data, I just needed a small amount of data with correct feature dimensions and realistic value ranges.

**Comment by RandomDefaultUser** [comment]
Oh, and nr just means number :sweat_smile:

**Comment by RandomDefaultUser** [comment]
I updated the README further, what do you think?

**Comment by elcorto** [comment]
Thanks a lot! Please have a look at #3. Then we can close this one.

**Comment by RandomDefaultUser** [comment]
Thanks! Looks great to me.
