### ISSUE TITLE
Get rid of Al36 data

### ISSUE THREAD

**Issue by RandomDefaultUser** [mala-project/test-data#2]
We don't really need them, Be2 covers everything they do and more.

**Comment by srajama1** [comment]
What is the accuracy one would expect on Be2 data. I was surprised by the low accuracy one would get on Al36 data while running the examples. I thought it was because we didn't have it tuned. Will Be2 be better?

**Comment by RandomDefaultUser** [comment]
Do you mean low accuracy in terms of loss or energy values? In terms of loss I think they should both be comparable, which is not to say super good, I never really tuned them at all. 
In terms of energies, the Be is way better. For example, using simply the small example networks I get e.g.:

```
Band energy (actual, predicted, error)[eV] 12.424254081462436 12.79562057025893 0.37136648879649314
Total energy (actual, predicted, error)[eV] -72.59824982045231 -72.20972534347281 0.388524476979498
```

which of course translates to ~185 meV/atom, but even this is not too bad given that I sampled the LDOS with only 11 points instead of 250 and used a very small k-point sampling in creating the data.

**Comment by srajama1** [comment]
Ok, let us use Be as the default for test repo. I will check with Aidan and Normand if there is an use case for keeping Al.

**Comment by RandomDefaultUser** [comment]
Sure, let me know! It also would not be a problem to keep the Al data if need be, it would just make the repo smaller if we didn't have to keep it.

**Comment by elcorto** [comment]
Since this repo doesn't use `git-lfs`, unless history is rewritten it will still be in `.git` so you'd save only the space required to unpack that into the working tree, which is 37 MiB, but better than nothing.

**Comment by RandomDefaultUser** [comment]
Ah yes, you're right...

**Comment by RandomDefaultUser** [comment]
Reminder, as mentioned in #1 : Also clean up the Be_ldos.npy while I'm on the Al data.
